# Generated by Django 2.0.7 on 2018-07-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medications',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
