# Generated by Django 2.0.7 on 2018-07-28 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # dependencies = [
    #     ('athletes_api', '0001_initial'),
    # ]

    operations = [
        migrations.CreateModel(
            name='ProfileFeedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='medications',
        ),
        migrations.AddField(
            model_name='profilefeeditems',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
