# Generated by Django 2.0.7 on 2018-08-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    # dependencies = [
    #     ('athletes_api', '0003_auto_20180728_2325'),
    # ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeedItems',
            new_name='ProfileFeedItem',
        ),
    ]
